### ISSUE TITLE
Widget length not updated 

### ISSUE THREAD

**Issue by fvisticot** [leocavalcante/page_view_indicator#1]
I'm using the PageViewIndicator inside a StreamBuilder.
The streamBuilder returns a List of object.
When object is added in the list and the StreamBuilder is triggered, the PageViewIndicator is NOT updated (number of dot stays the same).

If I try to insert a "basic" Text Widget, the Text is updated correctly with the number of objects in my list

**Comment by leocavalcante** [comment]
Hi @fvisticot 
Can you share a minimal code example so I can reproduce the behavior on my machine?

**Comment by leocavalcante** [comment]
Closed due inactivity.
