### ISSUE TITLE
Page Indicator overflowed, if we have many Pages

### ISSUE THREAD

**Issue by ParagSaini** [leocavalcante/page_view_indicator#19]
The issue is this, if  I use the Page Indicator and set the length property to a large value, it overflowed from the screen which make the app look like it crashes.
The code is 
PageViewIndicator(
      pageIndexNotifier: _currentPageNotifier,
      length: 20,
      indicatorPadding: EdgeInsets.all(5.0),
      normalBuilder: (animationController, index) => Circle(
        size: 8.0,
        color: Colors.black87,
      ),
      highlightedBuilder: (animationController, index) => ScaleTransition(
        scale: CurvedAnimation(
          parent: animationController,
          curve: Curves.ease,
        ),
        child: Circle(
          size: 20.0,
          color: Colors.grey,
        ),
      ),
    );
![Screenshot_1592486410](https://user-images.githubusercontent.com/50588553/85025202-b2b98400-b194-11ea-8673-f15a82e53b4e.png)

**Comment by leocavalcante** [comment]
Try to wrap it in a horizontal list: https://flutter.dev/docs/cookbook/lists/horizontal-list

**Comment by ParagSaini** [comment]
I tried it, but only problem with using the ListView is, once you crossed the last page of the page indicator shown on screen, you can't see where your page indicator is currently at.

**Comment by leocavalcante** [comment]
You will probably need a [`ScrollController`](https://api.flutter.dev/flutter/widgets/ScrollController-class.html) then sync its offset/position through `animateTo` or `jumpTo` with the current value of `pageIndexNotifier`.
