### ISSUE TITLE
HighlightedBuilder is called only once

### ISSUE THREAD

**Issue by dawidhyzy** [leocavalcante/page_view_indicator#7]
I want to change the color of the highlight depending on the index but currently, highlightedBuilder is called only once. How to workaround that?

**Comment by dawidhyzy** [comment]
👋

**Comment by leocavalcante** [comment]
Will work on something, probably passing the `index` after the `controller` on the builder function.

**Comment by leocavalcante** [comment]
Here we go :) 
https://github.com/leocavalcante/page_view_indicator/blob/master/example/lib/main.dart#L46
