### ISSUE TITLE
How do you adjust padding or spaces between the dots? 

### ISSUE THREAD

**Issue by ojiofong** [leocavalcante/page_view_indicator#9]
Great work on this. How do you adjust padding or spaces between the dots? For instance, I might want the dots to be aligned much closer together. How can this be achieved? If possible, it will be helpful to include that somewhere in the README.md examples.

**Comment by leocavalcante** [comment]
There we go: https://github.com/leocavalcante/page_view_indicator#changing-the-space-bettwen-the-indicators
